include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  errors:
    unused_import: warning
    deprecated_member_use: ignore

linter:
  rules:
    prefer_single_quotes: true
    sort_child_properties_last: true